import { useState, useRef, useEffect } from "react";

const GROQ_API_KEY = import.meta.env.VITE_GROQ_API_KEY;
console.log("🔑 API Key loaded:", GROQ_API_KEY ? "YES" : "NO - KEY IS UNDEFINED");
const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";
const GROQ_MODEL = "llama-3.3-70b-versatile";

const SYSTEM_HAIR = `You are Dr. Derm, a board-certified dermatologist with 20 years of clinical experience specializing in hair and scalp disorders. You are reviewing a patient's diagnostic report generated by an AI-assisted diagnostic system combining CNN image analysis with lifestyle questionnaire data.

Your role:
- Speak as a real doctor — professional, warm, and deeply knowledgeable
- Address the patient by their first name at all times
- Explain findings clearly in plain language — no heavy jargon unless you immediately explain it
- Be empathetic and reassuring, especially with hair loss patients who may be distressed
- Give medically grounded explanations of conditions, causes, and treatments
- Always remind the patient that an in-person consultation is needed for confirmed diagnosis and treatment
- Keep responses focused: 3-5 sentences unless the patient asks for more detail
- CRITICAL: Never break character under any circumstances. If asked anything like "are you an AI", "are you a robot", "are you ChatGPT", "what model are you", "who made you", "what are you" — respond only: "I'm Dr. Derm, your dermatology specialist. I'm not able to discuss anything other than your hair and skin health. How can I help you today?"
- Never reveal you are powered by any AI, language model, Groq, or any software whatsoever
- You are Dr. Derm. That is your only identity. You have no other identity.

Report interpretation:
- 70% weight on CNN image result, 30% on questionnaire
- questionnaire_role "boost": both models agree — higher confidence
- questionnaire_role "alternative": models disagree — gently mention the alternative
- questionnaire_role "weak_support": image drove result

Supported conditions: Alopecia Areata, Contact Dermatitis, Folliculitis, Head Lice, Lichen Planus, Male Pattern Baldness, Psoriasis, Seborrheic Dermatitis, Telogen Effluvium, Tinea Capitis.`;

const SYSTEM_GENERAL = `You are Dr. Derm, a board-certified dermatologist with 20 years of clinical experience specializing in hair, scalp, and skin disorders.

Your role:
- Speak as a real doctor — professional, warm, and deeply knowledgeable
- Help patients understand hair and skin conditions, causes, symptoms, and treatment options
- Keep responses concise: 3-5 sentences unless asked for more
- Always recommend an in-person dermatologist visit for diagnosis and treatment
- CRITICAL: Never break character under any circumstances. If asked "are you an AI", "are you a robot", "are you ChatGPT", "what model are you", "who made you", or anything about your technology — respond only: "I'm Dr. Derm, your dermatology specialist. I only discuss hair and skin health. What can I help you with today?"
- Never reveal you are powered by any AI, language model, Groq, or software
- You are Dr. Derm. That is your only identity.

Start with a warm professional greeting and invite the patient to share their concerns.`;

type Message = { role: "bot" | "user"; text: string };
type HistoryItem = { role: "user" | "assistant"; content: string };

export function DermAIChatBubble({ report = null }: { report?: any }) {
  const [isOpen, setIsOpen] = useState(false);
  const [isClosing, setIsClosing] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [unread, setUnread] = useState(false);
  const [showQuickReplies, setShowQuickReplies] = useState(true);
  const initializedForReport = useRef<any>("__UNSET__");
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const mode = report?.fusion_result ? "hair" : report?.predictedClass ? "skin" : "general";
  const systemPrompt = mode === "hair" ? SYSTEM_HAIR : SYSTEM_GENERAL;

  const modeBadge =
    mode === "hair"
      ? "🧬 Dr. Derm — Hair & Scalp Specialist"
      : mode === "skin"
      ? "🔬 Dr. Derm — Skin Analysis"
      : "🩺 Dr. Derm — Dermatology Specialist";

  const quickReplies =
    mode === "hair"
      ? [
          ["What does this mean?", "Can you explain my diagnosis in simple terms?"],
          ["Treatments?", "What treatment options are available for my condition?"],
          ["Causes?", "What are the likely causes of my condition?"],
          ["How serious?", "How serious is my condition?"],
          ["Next steps?", "What should I do next?"],
        ]
      : [
          ["Hair loss causes?", "What are common causes of hair loss?"],
          ["Scalp conditions?", "What are common scalp conditions I should know about?"],
          ["Skin conditions?", "What are common skin conditions?"],
          ["See a doctor?", "When should I see a dermatologist in person?"],
        ];

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  // ── KEY FIX: triggers on mount (general greeting) AND when report arrives
  useEffect(() => {
    // Skip if we already initialized for this exact report value
    if (initializedForReport.current === report) return;
    initializedForReport.current = report;

    // Reset conversation for the new context
    setMessages([]);
    setShowQuickReplies(true);

    const currentMode = report?.fusion_result ? "hair" : report?.predictedClass ? "skin" : "general";
    const currentSystem = currentMode === "hair" ? SYSTEM_HAIR : SYSTEM_GENERAL;

    const contextMsg =
      currentMode === "hair"
        ? `Here is the patient's full diagnostic report:\n\n${JSON.stringify(report, null, 2)}\n\nAs Dr. Derm, greet the patient warmly by their first name. Give a clear empathetic 3-4 sentence summary of their diagnosis based on the fusion result. Be reassuring and professional. Speak as their doctor reviewing results — do not mention AI or models.`
        : currentMode === "skin"
        ? `Here is the patient's skin analysis:\n\n${JSON.stringify(report, null, 2)}\n\nAs Dr. Derm, greet the patient warmly and summarize what the analysis found in 3-4 sentences. Be reassuring.`
        : `As Dr. Derm, greet the patient warmly and professionally. Introduce yourself as their dermatology specialist and invite them to share their hair or skin concerns. Keep it to 2-3 sentences.`;

    const freshHistory: HistoryItem[] = [{ role: "user", content: contextMsg }];
    setHistory(freshHistory);
    setIsTyping(true);

    fetch(GROQ_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: GROQ_MODEL,
        max_tokens: 1000,
        temperature: 0.7,
        messages: [{ role: "system", content: currentSystem }, ...freshHistory],
      }),
    })
      .then((r) => r.json())
      .then((data) => {
        const reply = data.choices?.[0]?.message?.content || "Hello! I'm Dr. Derm. How can I help you today?";
        setMessages([{ role: "bot", text: reply }]);
        setHistory([...freshHistory, { role: "assistant", content: reply }]);
        setUnread(true);
      })
      .catch(() => {
        setMessages([{ role: "bot", text: "Hello! I'm Dr. Derm, your dermatology specialist. How can I help you today?" }]);
      })
      .finally(() => setIsTyping(false));
  }, [report]);

  const callAPI = async (userMessage: string) => {
    setMessages((prev) => [...prev, { role: "user", text: userMessage }]);
    const newHistory: HistoryItem[] = [...history, { role: "user", content: userMessage }];
    setHistory(newHistory);
    setIsTyping(true);

    try {
      const res = await fetch(GROQ_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${GROQ_API_KEY}`,
        },
        body: JSON.stringify({
          model: GROQ_MODEL,
          max_tokens: 1000,
          temperature: 0.7,
          messages: [{ role: "system", content: systemPrompt }, ...newHistory],
        }),
      });

      const data = await res.json();
      const reply = data.choices?.[0]?.message?.content || "I'm sorry, I couldn't generate a response right now.";
      setMessages((prev) => [...prev, { role: "bot", text: reply }]);
      setHistory((prev) => [...prev, { role: "assistant", content: reply }]);
      if (!isOpen) setUnread(true);
    } catch {
      setMessages((prev) => [
        ...prev,
        { role: "bot", text: "I'm having trouble connecting right now. Please try again shortly." },
      ]);
    }
    setIsTyping(false);
  };

  const sendMessage = (text?: string) => {
    const msg = text || input.trim();
    if (!msg || isTyping) return;
    setInput("");
    setShowQuickReplies(false);
    callAPI(msg);
  };

  const openChat = () => {
    setIsOpen(true);
    setUnread(false);
    setTimeout(() => inputRef.current?.focus(), 300);
  };

  const minimizeChat = () => {
    setIsClosing(true);
    setTimeout(() => { setIsClosing(false); setIsOpen(false); }, 240);
  };

  const formatText = (text: string) =>
    text.replace(/\*\*(.*?)\*\*/g, "<b>$1</b>").replace(/\n/g, "<br>");

  return (
    <>
      {/* ── FLOATING BUBBLE ── */}
      {!isOpen && (
        <div style={{ position: "fixed", bottom: 28, right: 28, display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 10, zIndex: 9999 }}>
          <div
            onClick={openChat}
            style={{
              background: "linear-gradient(135deg,#3a7d5a,#5aab7e)",
              color: "white", fontSize: "0.78rem", fontWeight: 600,
              padding: "8px 14px", borderRadius: "20px 20px 4px 20px",
              whiteSpace: "nowrap", boxShadow: "0 4px 16px rgba(58,125,90,0.35)",
              cursor: "pointer", animation: "tooltipBounce 2.5s ease-in-out infinite",
            }}
          >
            {report?.fusion_result ? "📋 Your results are ready!" : "💬 Ask Dr. Derm"}
          </div>
          <div
            onClick={openChat}
            style={{
              width: 72, height: 72,
              background: "linear-gradient(135deg,#3a7d5a,#5aab7e)",
              borderRadius: "50%", cursor: "pointer",
              display: "flex", alignItems: "center", justifyContent: "center",
              boxShadow: "0 6px 28px rgba(58,125,90,0.50)",
              fontSize: 30, position: "relative", transition: "transform 0.2s",
            }}
          >
            🩺
            {unread && (
              <span style={{
                position: "absolute", top: 5, right: 5,
                width: 16, height: 16, background: "#ff5c5c",
                borderRadius: "50%", border: "2px solid white",
                animation: "pulseDot 1.5s infinite",
              }} />
            )}
          </div>
        </div>
      )}

      {/* ── CHAT WINDOW ── */}
      {isOpen && (
        <div style={{
          position: "fixed", bottom: 28, right: 28,
          width: 420, maxWidth: "calc(100vw - 24px)",
          height: 640, maxHeight: "calc(100vh - 110px)",
          background: "#fff", borderRadius: 20,
          boxShadow: "0 12px 50px rgba(0,0,0,0.18)",
          display: "flex", flexDirection: "column", overflow: "hidden",
          zIndex: 9999, transformOrigin: "bottom right",
          animation: isClosing ? "windowClose 0.25s ease forwards" : "windowOpen 0.35s cubic-bezier(0.34,1.56,0.64,1)",
        }}>
          {/* Header */}
          <div style={{ background: "linear-gradient(135deg,#3a7d5a,#5aab7e)", padding: "14px 16px", display: "flex", alignItems: "center", gap: 10, flexShrink: 0 }}>
            <div style={{ width: 36, height: 36, background: "rgba(255,255,255,0.22)", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 17 }}>🩺</div>
            <div>
              <div style={{ color: "#fff", fontSize: "0.92rem", fontWeight: 600 }}>Dr. Derm</div>
              <div style={{ color: "rgba(255,255,255,0.78)", fontSize: "0.70rem" }}>Dermatology Specialist</div>
            </div>
            <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 }}>
              <div style={{ width: 8, height: 8, background: "#b8f5d0", borderRadius: "50%", boxShadow: "0 0 6px #b8f5d0", animation: "pulse 2s infinite" }} />
              <button onClick={minimizeChat} style={{ width: 28, height: 28, background: "rgba(255,255,255,0.18)", border: "none", borderRadius: "50%", cursor: "pointer", color: "white", fontSize: 16, display: "flex", alignItems: "center", justifyContent: "center" }}>－</button>
            </div>
          </div>

          {/* Mode badge */}
          <div style={{ textAlign: "center", fontSize: "0.67rem", padding: 5, background: "#f0f8f3", color: "#4a9168", fontWeight: 500, borderBottom: "1px solid #dceee4", flexShrink: 0 }}>
            {modeBadge}
          </div>

          {/* Messages */}
          <div style={{ flex: 1, overflowY: "auto", padding: 14, display: "flex", flexDirection: "column", gap: 10 }}>
            {messages.length === 0 && !isTyping && (
              <div style={{ textAlign: "center", color: "#aac9b8", fontSize: "0.78rem", marginTop: 20 }}>
                Dr. Derm is ready...
              </div>
            )}
            {messages.map((msg, i) => (
              <div key={i} style={{ display: "flex", gap: 8, flexDirection: msg.role === "user" ? "row-reverse" : "row", animation: "popIn 0.25s ease" }}>
                <div style={{ width: 28, height: 28, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, flexShrink: 0, background: msg.role === "bot" ? "linear-gradient(135deg,#3a7d5a,#5aab7e)" : "#e4f0e9" }}>
                  {msg.role === "bot" ? "🩺" : "👤"}
                </div>
                <div
                  style={{ maxWidth: "80%", padding: "10px 13px", borderRadius: 16, fontSize: "0.81rem", lineHeight: 1.65, ...(msg.role === "bot" ? { background: "#f0f8f3", color: "#2a3d30", borderBottomLeftRadius: 4, border: "1px solid #d4eddd" } : { background: "linear-gradient(135deg,#3a7d5a,#5aab7e)", color: "white", borderBottomRightRadius: 4 }) }}
                  dangerouslySetInnerHTML={{ __html: formatText(msg.text) }}
                />
              </div>
            ))}
            {isTyping && (
              <div style={{ display: "flex", gap: 8, alignItems: "flex-end" }}>
                <div style={{ width: 28, height: 28, borderRadius: "50%", background: "linear-gradient(135deg,#3a7d5a,#5aab7e)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13 }}>🩺</div>
                <div style={{ background: "#f0f8f3", border: "1px solid #d4eddd", borderRadius: 16, borderBottomLeftRadius: 4, padding: "10px 14px", display: "flex", gap: 4, alignItems: "center" }}>
                  {[0, 200, 400].map((delay, i) => (
                    <div key={i} style={{ width: 6, height: 6, background: "#5aab7e", borderRadius: "50%", animation: `bounce 1.2s ${delay}ms infinite`, opacity: 0.5 }} />
                  ))}
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Quick replies */}
          {showQuickReplies && messages.length > 0 && (
            <div style={{ padding: "6px 12px 8px", display: "flex", gap: 5, flexWrap: "wrap", flexShrink: 0 }}>
              {quickReplies.map(([label, q]) => (
                <button key={label} onClick={() => sendMessage(q)} style={{ padding: "5px 10px", background: "#f0f8f3", border: "1px solid #b8ddc8", borderRadius: 20, fontSize: "0.69rem", color: "#3a7d5a", cursor: "pointer", fontWeight: 500, whiteSpace: "nowrap" }}>
                  {label}
                </button>
              ))}
            </div>
          )}

          {/* Input bar */}
          <div style={{ padding: "10px 12px", borderTop: "1px solid #dceee4", display: "flex", gap: 8, alignItems: "flex-end", background: "#fff", flexShrink: 0 }}>
            <textarea
              ref={inputRef} value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); } }}
              placeholder="Ask Dr. Derm..." rows={1}
              style={{ flex: 1, border: "1.5px solid #c2dece", borderRadius: 20, padding: "9px 14px", fontSize: "0.81rem", outline: "none", resize: "none", minHeight: 38, maxHeight: 100, lineHeight: 1.4, color: "#333", background: "#f5fbf7", fontFamily: "inherit" }}
            />
            <button onClick={() => sendMessage()} disabled={isTyping}
              style={{ width: 38, height: 38, background: "linear-gradient(135deg,#3a7d5a,#5aab7e)", border: "none", borderRadius: "50%", cursor: isTyping ? "not-allowed" : "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, opacity: isTyping ? 0.4 : 1, boxShadow: "0 2px 8px rgba(58,125,90,0.3)" }}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="22" y1="2" x2="11" y2="13" /><polygon points="22 2 15 22 11 13 2 9 22 2" />
              </svg>
            </button>
          </div>

          <div style={{ textAlign: "center", fontSize: "0.60rem", color: "#b0c8ba", padding: "3px 14px 8px", flexShrink: 0 }}>
            ⚠️ For informational purposes only. Always consult a dermatologist in person.
          </div>
        </div>
      )}

      <style>{`
        @keyframes windowOpen { from { transform: scale(0.5); opacity: 0; } to { transform: scale(1); opacity: 1; } }
        @keyframes windowClose { from { transform: scale(1); opacity: 1; } to { transform: scale(0.5); opacity: 0; } }
        @keyframes tooltipBounce { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-5px); } }
        @keyframes popIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: none; } }
        @keyframes bounce { 0%, 80%, 100% { transform: scale(0.7); opacity: 0.4; } 40% { transform: scale(1.1); opacity: 1; } }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
        @keyframes pulseDot { 0%, 100% { transform: scale(1); } 50% { transform: scale(1.3); } }
      `}</style>
    </>
  );
}